#!/usr/bin/env bash
page_name=$1
page_content="
@extends('layouts.dashboard')\n
@section('title') \n
${page_name} \n
@endsection \n
@section('content') \n
 <p> This is the ${page_name} page </p> \n
@endsection()"

touch resources/views/dashboard/${page_name}.blade.php
echo -e ${page_content} >> resources/views/dashboard/${page_name}.blade.php
